# SPDX-License-Identifier: BUSL-1.1
# Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four years from publication; Change License: Apache-2.0
# Copyright (c) 2026 Empower Agile
# The single source of truth for the version of everything this repo publishes.
# The 17 library modules AND the Gradle plugin share it: the plugin resolves the
# library version from its own version (VersionResolver reads the generated
# narrativetrace-version.properties), so a plugin on a different number would
# install mismatched libraries. Bump here, and the release moves as one unit.
narrativetraceVersion=0.2.0
