/*
 * Copyright (c) 2026 Empower Agile
 *
 * SPDX-License-Identifier: BUSL-1.1
 * Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four
 * years from publication; Change License: Apache-2.0
 */
import java.security.MessageDigest
import java.util.Properties

plugins {
    id("narrativetrace-publish")
    `java-test-fixtures`
}

extra["publishName"] = "NarrativeTrace Core"
extra["publishDescription"] = "Auto-generates human-readable execution traces from method and parameter names."

// Exclude test fixtures from Maven Central publication
components.named<AdhocComponentWithVariants>("java") {
    withVariantsFromConfiguration(configurations["testFixturesApiElements"]) { skip() }
    withVariantsFromConfiguration(configurations["testFixturesRuntimeElements"]) { skip() }
}

// --- Performance calibration: generated PerfThresholds.java ---

fun machineHash(): String {
    val input = listOf(
        System.getenv("COMPUTERNAME") ?: System.getenv("HOSTNAME") ?: "unknown",
        Runtime.getRuntime().availableProcessors().toString(),
        System.getProperty("os.arch"),
        System.getProperty("os.name")
    ).joinToString("|")
    val digest = MessageDigest.getInstance("SHA-256").digest(input.toByteArray(Charsets.UTF_8))
    return digest.take(4).joinToString("") { "%02x".format(it) }
}

// name, p90RefMs, p99RefMs, minOpsRef
// Reference thresholds: name, p90ms, p99ms, minOpsPerSec
// Latency = max allowed; ops = min required. At factor=1.0 (reference machine).
// Thresholds set at 120% of measured baseline (20% headroom).
val perfReferenceThresholds = listOf(
    arrayOf("CORE_ENTER_EXIT",     "0.001", "0.010", "200000"),
    arrayOf("CORE_TREE_BUILD",     "0.100", "0.500", "100000"),
    arrayOf("CORE_VALUE_RENDER",   "0.001", "0.010", "340000"),
    arrayOf("SLF4J_EVENT_LISTENER","0.010", "0.050", "100000"),
    arrayOf("SERVLET_FILTER",      "0.050", "0.200", "100000"),
    arrayOf("SPRING_BPP",          "0.100", "0.500", "50000"),
    arrayOf("SPRING_WEB_FILTER",   "0.050", "0.200", "100000"),
    arrayOf("PROXY_INVOKE",        "0.050", "0.200", "100000")
)

val generatePerfThresholds = tasks.register("generatePerfThresholds") {
    group = "verification"
    description = "Generates PerfThresholds.java with calibrated constants"
    val outputDir = layout.buildDirectory.dir("generated/testFixtures/java")
    val calibrationDir = rootProject.file("perf-calibration")
    outputs.dir(outputDir)
    inputs.files(fileTree(calibrationDir) { include("*.properties") })
    doLast {
        val hash = machineHash()
        val calibrationFile = File(calibrationDir, "$hash.properties")
        val factor = if (calibrationFile.exists()) {
            val props = Properties()
            calibrationFile.inputStream().use { props.load(it) }
            props.getProperty("calibration.factor")?.toDoubleOrNull() ?: 1.0
        } else {
            System.err.println("[perf] No calibration for machine $hash — using factor 1.0")
            1.0
        }

        val dir = File(outputDir.get().asFile, "ai/narrativetrace/perf")
        dir.mkdirs()
        val sb = StringBuilder()
        sb.appendLine("/*")
        sb.appendLine(" * Generated by generatePerfThresholds — do not edit manually.")
        sb.appendLine(" * Machine: $hash, factor: ${"%.4f".format(factor)}")
        sb.appendLine(" */")
        sb.appendLine("package ai.narrativetrace.perf;")
        sb.appendLine()
        sb.appendLine("/** Calibrated performance thresholds for {@code @JUnitPerfTestRequirement}. */")
        sb.appendLine("public final class PerfThresholds {")
        sb.appendLine("  private PerfThresholds() {}")
        sb.appendLine()
        sb.appendLine("  public static final double MACHINE_FACTOR = ${"%.4f".format(factor)};")
        sb.appendLine()
        for (t in perfReferenceThresholds) {
            val name = t[0]
            val p90 = "%.3f".format(t[1].toDouble() / factor)
            val p99 = "%.3f".format(t[2].toDouble() / factor)
            val ops = (t[3].toInt() * factor).toInt()
            sb.appendLine("  public static final String ${name}_PERCENTILES = \"90:$p90,99:$p99\";")
            sb.appendLine("  public static final int ${name}_MIN_OPS = $ops;")
            sb.appendLine()
        }
        sb.appendLine("}")
        File(dir, "PerfThresholds.java").writeText(sb.toString())
        println("[perf] Generated PerfThresholds.java (factor=${"%.4f".format(factor)})")
    }
}

sourceSets.named("testFixtures") {
    java.srcDir(generatePerfThresholds.map {
        layout.buildDirectory.dir("generated/testFixtures/java").get()
    })
}

tasks.named("compileTestFixturesJava") {
    dependsOn(generatePerfThresholds)
}

dependencies {
    // `api`, not `implementation`: every module that depends on core compiles against the
    // annotation, event and SPI types, so they must stay on the consumer's compile classpath.
    api(project(":narrativetrace-api"))

    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
    testImplementation("org.assertj:assertj-core:3.27.7")
    testImplementation("net.jqwik:jqwik:1.9.2")
    testImplementation("com.tngtech.archunit:archunit-junit5:1.4.0")
    testImplementation("com.networknt:json-schema-validator:1.5.6")
    // json-schema-validator 1.5.6 pulls a jackson-databind/jackson-core with open
    // advisories (GHSA-3pjw-73gf-8qr5 and siblings; found by osvScan). No 1.x release
    // fixes it and 3.0.7 is a breaking major jump (out of scope here), so the floor is
    // raised directly instead — the same pin narrativetrace-security-tests already uses.
    testImplementation("com.fasterxml.jackson.core:jackson-databind:2.18.10")

    testFixturesImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
    testFixturesImplementation("org.assertj:assertj-core:3.27.7")
    testFixturesImplementation("com.github.noconnor:junitperf-junit5:1.37.0")

    testImplementation(testFixtures(project(":narrativetrace-core")))
    testImplementation(testFixtures(project(":narrativetrace-api")))
    testImplementation("com.github.noconnor:junitperf-junit5:1.37.0")
}
