/*
 * Copyright (c) 2026 Empower Agile
 *
 * SPDX-License-Identifier: BUSL-1.1
 * Licensed under the Business Source License 1.1 (see LICENSE); Change Date: four
 * years from publication; Change License: Apache-2.0
 */
package ai.narrativetrace.glossary;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;

class GlossaryMarkdownRendererTest {

  private final GlossaryMarkdownRenderer renderer = new GlossaryMarkdownRenderer();

  @Test
  void rendersContextSectionsWithOneTablePerKind() {
    var glossary =
        new Glossary(
            1,
            Map.of(
                "billing",
                    new BoundedContext(
                        "billing",
                        List.of("com.acme.billing", "com.acme.funds"),
                        "Charging, invoicing, funds"),
                "_unassigned", new BoundedContext("_unassigned", List.of(), null)),
            List.of(
                new GlossaryTerm(
                    "overdraft account",
                    "billing",
                    TermKind.NOUN_PHRASE,
                    TermStatus.CURATED,
                    "Account permitted to go below zero.",
                    Map.of("es", "cuenta con descubierto", "de", "Dispokonto"),
                    List.of(
                        new SynonymAlias("account with overdraft", "legacy v1 API phrasing"),
                        new SynonymAlias("minus account", null)),
                    List.of(),
                    LocalDate.of(2026, 8, 11)),
                new GlossaryTerm(
                    "charge",
                    "billing",
                    TermKind.VERB_PHRASE,
                    TermStatus.HARVESTED,
                    null,
                    Map.of(),
                    List.of(),
                    List.of(),
                    LocalDate.of(2026, 8, 11)),
                new GlossaryTerm(
                    "ticket",
                    "_unassigned",
                    TermKind.WORD,
                    TermStatus.HARVESTED,
                    null,
                    Map.of(),
                    List.of(),
                    List.of(),
                    LocalDate.of(2026, 8, 12))));

    var markdown = renderer.render(glossary);

    assertThat(markdown)
        .isEqualTo(
            """
            # Domain Glossary

            Generated from `glossary.json` — edit the JSON, then regenerate; do not edit this file.

            ## _unassigned

            ### Words

            | Term | Status | Definition | Deprecated synonyms | Translations |
            |---|---|---|---|---|
            | ticket | harvested |  |  |  |

            ## billing

            Charging, invoicing, funds

            Packages: `com.acme.billing`, `com.acme.funds`

            ### Noun phrases

            | Term | Status | Definition | Deprecated synonyms | Translations |
            |---|---|---|---|---|
            | overdraft account | curated | Account permitted to go below zero. | account with overdraft — legacy v1 API phrasing; minus account | de: Dispokonto; es: cuenta con descubierto |

            ### Verb phrases

            | Term | Status | Definition | Deprecated synonyms | Translations |
            |---|---|---|---|---|
            | charge | harvested |  |  |  |
            """);
  }

  @Test
  void escapesPipesAndNewlinesInTableCells() {
    var glossary =
        new Glossary(
            1,
            Map.of("billing", new BoundedContext("billing", List.of(), null)),
            List.of(
                new GlossaryTerm(
                    "pipe term",
                    "billing",
                    TermKind.WORD,
                    TermStatus.CURATED,
                    "a | b\nc",
                    Map.of(),
                    List.of(),
                    List.of(),
                    LocalDate.of(2026, 8, 11))));

    var markdown = renderer.render(glossary);

    assertThat(markdown).contains("| pipe term | curated | a \\| b c |");
  }

  @Test
  void rendersTemplateKindUnderTemplatesHeading() {
    var glossary =
        new Glossary(
            1,
            Map.of("billing", new BoundedContext("billing", List.of(), null)),
            List.of(
                new GlossaryTerm(
                    "charging {amount}",
                    "billing",
                    TermKind.TEMPLATE,
                    TermStatus.HARVESTED,
                    null,
                    Map.of(),
                    List.of(),
                    List.of(),
                    LocalDate.of(2026, 8, 11))));

    assertThat(renderer.render(glossary)).contains("### Templates");
  }

  @Test
  void rejectsNullGlossary() {
    org.assertj.core.api.Assertions.assertThatIllegalArgumentException()
        .isThrownBy(() -> renderer.render(null))
        .withMessageContaining("glossary");
  }

  @Test
  void rendersTheAcceptedAbbreviationsSectionAboveTheContexts() {
    var glossary =
        new Glossary(2, Map.of(), Map.of("fx", "foreign exchange", "calc", "calculate"), List.of());

    var markdown = renderer.render(glossary);

    assertThat(markdown)
        .contains("## Accepted abbreviations")
        .contains("| Abbreviation | Stands for |")
        .contains("| calc | calculate |")
        .contains("| fx | foreign exchange |");
    assertThat(markdown.indexOf("| calc | calculate |"))
        .as("sorted by abbreviation, so the document does not churn")
        .isLessThan(markdown.indexOf("| fx | foreign exchange |"));
  }

  @Test
  void omitsTheAbbreviationsSectionWhenNoneAreDeclared() {
    assertThat(renderer.render(new Glossary(1, Map.of(), List.of())))
        .doesNotContain("Accepted abbreviations");
  }

  @Test
  void escapesPipesInAnAbbreviationExpansion() {
    var glossary = new Glossary(2, Map.of(), Map.of("ab", "a | b"), List.of());

    assertThat(renderer.render(glossary)).contains("| ab | a \\| b |");
  }
}
